name: Load Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  load:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68
        with:
          dotnet-version: '8.0.x'
      - name: Load tests
        run: dotnet test tests/Flumewright.LoadTests --filter "Category=Load" --configuration Release
