name: Load Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  load:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2
        with:
          dotnet-version: '8.0.x'
      - name: Load tests
        run: dotnet test tests/Flumewright.LoadTests --filter "Category=Load" --configuration Release
